In [ ]:
import random
import numpy as np
import timeit
import matplotlib.pyplot as plt
import seaborn as sns

n = 100
time = []
xs = list(map(int, range(n)))

def monkey_sort(x):
    def is_sorted(lst):
        return all(lst[i + 1] >= lst[i] for i in range(len(lst) - 1))

    def monkey(lst):
        while not is_sorted(lst):
            random.shuffle(lst)
        return(lst)

    monkey(x)
    return x

for i in range(1, n + 1):
    List = np.random.sample(i)
    print(monkey_sort(List))
    time.append(timeit.timeit("monkey_sort(List)", setup="from __main__ import monkey_sort, List", number=1))
    
print(time)

#plotting
plt.rcParams['figure.figsize'] = [10, 6] #the size of image
plt.rcParams['font.size'] = 12 #the size of values
plt.rcParams['savefig.bbox'] = 'tight'

#style, color of plots
plt.style.use('seaborn-darkgrid')
col = plt.get_cmap('Set1')

plt.plot(xs, time, color = col(1))
plt.title('NumPy VS Random: comparison of running time \n on the \
 example of generating random numbers of uniform distribution')
plt.ylabel('time, sec')
plt.xlabel('Length of the list')


[0.4774494]
[0.05245569 0.64253604]
[0.20249732 0.6429472  0.66030233]
[0.09390543 0.36052236 0.60504359 0.79167348]
[0.44151412 0.66202843 0.78793109 0.88528883 0.95181845]
[0.20688901 0.45523061 0.61936222 0.73793993 0.95599703 0.96278716]
[0.02021223 0.30409662 0.45443417 0.70619096 0.74863306 0.81995919
 0.84121531]
[0.01554828 0.13285732 0.32815329 0.42102739 0.44541158 0.56264354
 0.62658576 0.92989845]
[0.10293019 0.11492482 0.14476735 0.15420649 0.35481137 0.44318411
 0.52533348 0.66061458 0.81075176]
[0.05251559 0.0811379  0.25005503 0.26708789 0.31548198 0.55450079
 0.70189121 0.75069461 0.97226591 0.97781768]
